version: "2"
checks:
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 80
  method-count:
    config:
      threshold: 30
  method-lines:
    config:
      threshold: 150
  nested-control-flow:
    config:
      threshold: 6
  return-statements:
    config:
      threshold: 20
  identical-code:
    config:
      threshold: 60
engines:
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
        - python
        - php
  eslint:
    enabled: true
    channel: eslint-6
  fixme:
    enabled: true
ratings:
  paths:
    - "*.js"
    - "lib/*.js"
    - "lib/compiler/*.js"
    - "test/*.js"
exclude_patterns:
  - "**/reverse/"
  - "**/test/"
